<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Library</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.4" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.5" />
    <PackageReference Include="UI.for.WinForms.AllControls.Net80">
      <Version>2024.4.1113</Version>
    </PackageReference>
  </ItemGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties ShouldAddDPIScalingManifest="" />
    </VisualStudio>
  </ProjectExtensions>
</Project>